---

- hosts: all 
  remote_user: root
  tasks:
    - name: Ensure Apache2 is at the latest version
      apt: name=apache2 state=latest
    - name: Ensure Apache 2 is running
      service: name=apache2 state=started enasbled=yes

...